config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get  '/search', to: 'static_pages#search'
  post '/search', to: 'static_pages#searching'

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :microposts,             only: [:show, :new, :create, :destroy]
  resources :comments,               only: [:create, :destroy]
  resources :likes,                  only: [:index, :create, :destroy]
  resources :relationships,          only: [:create, :destroy]
  resources :notifications,          only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  scope :from_new_to_old, -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  validates :user_id, presence: true
  validates :image, presence: true
  validates :content, length: { maximum: 140 }
  validate :image_size

  # 検索ワードに該当する投稿があるか確認し無ければnilを返す
  def self.search(keyword)
    if keyword.present?
      if where("content LIKE ?", "%#{keyword}%").present?
        where("content LIKE ?", "%#{keyword}%")
      else
        nil
      end
    else
      nil
    end
  end

  # いいね！に対して通知を作成する
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(
      "visitor_id = :visitor and visited_id = :visited and
      micropost_id= :micropost and action= :action",
      visitor: current_user, visited: user_id, micropost: id, action: "like"
    )
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.build(
        micropost_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメントに対して通知を作成する
  def create_notification_comment!(current_user, comment_id)
    temp = Notification.where(
      "visitor_id= :visitor and visited_id = :visited and
      comment_id = :comment and action = :action",
      visitor: current_user, visited: user_id,
      comment: comment_id, action: "comment"
    )
    if temp.blank?
      notification = current_user.active_notifications.build(
        micropost_id: id,
        comment_id: comment_id,
        visited_id: user_id,
        action: 'comment'
      )
      # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy

  def show
    @micropost = Micropost.find(params[:id])
    @comment = current_user.comments.build
    @comments = @micropost.comments.from_new_to_old.paginate(page: params[:page], per_page: 10)
  end

  def new
    @micropost = current_user.microposts.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "画像が投稿されました。"
      redirect_to @micropost
    else
      flash.now[:danger] = "正しく入力して下さい。"
      render 'new'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました。"
    redirect_to root_path
  end

  private

  def micropost_params
    params.require(:micropost).permit(:image, :content)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/views/microposts/_micropost.html.erb
<li>
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <% unless micropost.image.blank? %>
      <%= link_to (image_tag micropost.image.url), micropost_path(micropost) %>
    <% end %>
      <%= micropost.content %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>前
  </span>
</li>

app/views/microposts/new.html.erb
<% provide(:title, 'New post') %>
<h1>新規投稿</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@micropost) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
        <%= f.label :image, "画像" %>
        <%= f.file_field :image, accept:"image/png,image/jpeg" %>
    
        <%= f.label :content, "コメント欄" %>
        <%= f.text_field :content, placeholder: "Compose new micropost..." %>
        
        <%= f.submit "投稿する", class: "btn btn-primary" %>
        
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/show.html.erb
<% provide(:title, "Micropost") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="image">
      <%= link_to gravatar_for(@micropost.user, size: 50), @micropost.user %>
    </h1>
    <h4 class="user"><%= link_to @micropost.user.name, @micropost.user %></h4>

    <section>
      <div class="content">
        <%= image_tag @micropost.image.url unless @micropost.image.blank?  %>
      </div>
      <div><%= @micropost.content %></div>
      <div class ="timestamp">
        <%= time_ago_in_words(@micropost.created_at) %>前
      </div>
      <div><%= render partial:'likes/like', micropost: @micropost %></div>
      <div>
        <% if current_user?(@micropost.user) %>
          <%= link_to "投稿を削除する", @micropost, method: :delete,
                                  data: { confirm: "本当に削除しますか?" },
                                  class:"btn btn-danger btn-sm" %>
        <% end %>
      </div>
      <div><%= render partial:'comments/comment_form' %></div>
      <p></p>
      <div class="col-md-6">
        <% if @comments.any? %>
        <ol class="microposts">
          <%= render @comments %>
        </ol>
        <%= will_paginate @comments %>
        <% end %>
      </div>
    </section>
  </div>
</div>