config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get  '/search', to: 'static_pages#search'
  post '/search', to: 'static_pages#searching'

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :microposts,             only: [:show, :new, :create, :destroy]
  resources :comments,               only: [:create, :destroy]
  resources :likes,                  only: [:index, :create, :destroy]
  resources :relationships,          only: [:create, :destroy]
  resources :notifications,          only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "新規投稿", new_micropost_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Original App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "お気に入り", likes_path %></li>
          <li><%= link_to "検索", search_path %></li>
          <li><%= link_to "通知", notifications_path %></li>
          <li><%= link_to "My page", user_path(current_user) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>